// seed-data.js — 頻度順フランス語300語（仮データ）
// 本番では1万語に置き換え。Wiktionary APIで生成予定。
window.SEED_VOCAB = [
  // 1-50: 最頻出（冠詞、代名詞、動詞、前置詞）
  { rank: 1, word: "le", translations: ["the (masc.)"], pos: "art" },
  { rank: 2, word: "de", translations: ["of", "from", "about"], pos: "prep" },
  { rank: 3, word: "un", translations: ["a", "one (masc.)"], pos: "art" },
  { rank: 4, word: "être", translations: ["to be"], pos: "v" },
  { rank: 5, word: "et", translations: ["and"], pos: "conj" },
  { rank: 6, word: "à", translations: ["to", "at"], pos: "prep" },
  { rank: 7, word: "il", translations: ["he", "it"], pos: "pron" },
  { rank: 8, word: "avoir", translations: ["to have"], pos: "v" },
  { rank: 9, word: "ne", translations: ["not"], pos: "adv" },
  { rank: 10, word: "je", translations: ["I"], pos: "pron" },
  { rank: 11, word: "son", translations: ["his", "her", "its"], pos: "adj" },
  { rank: 12, word: "que", translations: ["that", "which", "what"], pos: "pron" },
  { rank: 13, word: "se", translations: ["oneself"], pos: "pron" },
  { rank: 14, word: "qui", translations: ["who", "which"], pos: "pron" },
  { rank: 15, word: "ce", translations: ["this", "that"], pos: "pron" },
  { rank: 16, word: "dans", translations: ["in", "into"], pos: "prep" },
  { rank: 17, word: "en", translations: ["in", "of it"], pos: "prep" },
  { rank: 18, word: "du", translations: ["of the", "from the"], pos: "prep" },
  { rank: 19, word: "elle", translations: ["she", "her"], pos: "pron" },
  { rank: 20, word: "au", translations: ["to the", "at the"], pos: "prep" },
  { rank: 21, word: "pour", translations: ["for", "in order to"], pos: "prep" },
  { rank: 22, word: "pas", translations: ["not", "step"], pos: "adv" },
  { rank: 23, word: "que", translations: ["than", "as"], pos: "conj" },
  { rank: 24, word: "vous", translations: ["you (formal/pl.)"], pos: "pron" },
  { rank: 25, word: "par", translations: ["by", "through"], pos: "prep" },
  { rank: 26, word: "sur", translations: ["on", "about"], pos: "prep" },
  { rank: 27, word: "faire", translations: ["to do", "to make"], pos: "v" },
  { rank: 28, word: "plus", translations: ["more", "no longer"], pos: "adv" },
  { rank: 29, word: "dire", translations: ["to say", "to tell"], pos: "v" },
  { rank: 30, word: "me", translations: ["me", "myself"], pos: "pron" },
  { rank: 31, word: "on", translations: ["one", "we", "people"], pos: "pron" },
  { rank: 32, word: "mon", translations: ["my (masc.)"], pos: "adj" },
  { rank: 33, word: "lui", translations: ["him", "to him/her"], pos: "pron" },
  { rank: 34, word: "nous", translations: ["we", "us"], pos: "pron" },
  { rank: 35, word: "comme", translations: ["like", "as"], pos: "conj" },
  { rank: 36, word: "mais", translations: ["but"], pos: "conj" },
  { rank: 37, word: "pouvoir", translations: ["to be able to", "can"], pos: "v" },
  { rank: 38, word: "avec", translations: ["with"], pos: "prep" },
  { rank: 39, word: "tout", translations: ["all", "everything"], pos: "adj" },
  { rank: 40, word: "y", translations: ["there", "to it"], pos: "pron" },
  { rank: 41, word: "aller", translations: ["to go"], pos: "v" },
  { rank: 42, word: "voir", translations: ["to see"], pos: "v" },
  { rank: 43, word: "bien", translations: ["well", "good"], pos: "adv" },
  { rank: 44, word: "où", translations: ["where"], pos: "adv" },
  { rank: 45, word: "sans", translations: ["without"], pos: "prep" },
  { rank: 46, word: "tu", translations: ["you (informal)"], pos: "pron" },
  { rank: 47, word: "ou", translations: ["or"], pos: "conj" },
  { rank: 48, word: "leur", translations: ["their", "to them"], pos: "pron" },
  { rank: 49, word: "homme", translations: ["man"], pos: "n" },
  { rank: 50, word: "si", translations: ["if", "so", "yes"], pos: "conj" },
  // 51-100: 次のレベル
  { rank: 51, word: "deux", translations: ["two"], pos: "num" },
  { rank: 52, word: "mari", translations: ["husband"], pos: "n" },
  { rank: 53, word: "moi", translations: ["me"], pos: "pron" },
  { rank: 54, word: "vouloir", translations: ["to want"], pos: "v" },
  { rank: 55, word: "te", translations: ["you", "yourself"], pos: "pron" },
  { rank: 56, word: "femme", translations: ["woman", "wife"], pos: "n" },
  { rank: 57, word: "venir", translations: ["to come"], pos: "v" },
  { rank: 58, word: "quand", translations: ["when"], pos: "conj" },
  { rank: 59, word: "grand", translations: ["big", "tall", "great"], pos: "adj" },
  { rank: 60, word: "celui", translations: ["the one (masc.)"], pos: "pron" },
  { rank: 61, word: "si", translations: ["so", "such"], pos: "adv" },
  { rank: 62, word: "notre", translations: ["our"], pos: "adj" },
  { rank: 63, word: "devoir", translations: ["must", "to owe"], pos: "v" },
  { rank: 64, word: "là", translations: ["there"], pos: "adv" },
  { rank: 65, word: "jour", translations: ["day"], pos: "n" },
  { rank: 66, word: "prendre", translations: ["to take"], pos: "v" },
  { rank: 67, word: "même", translations: ["same", "even"], pos: "adj" },
  { rank: 68, word: "trouver", translations: ["to find"], pos: "v" },
  { rank: 69, word: "donner", translations: ["to give"], pos: "v" },
  { rank: 70, word: "temps", translations: ["time", "weather"], pos: "n" },
  { rank: 71, word: "très", translations: ["very"], pos: "adv" },
  { rank: 72, word: "savoir", translations: ["to know"], pos: "v" },
  { rank: 73, word: "falloir", translations: ["to be necessary"], pos: "v" },
  { rank: 74, word: "voilà", translations: ["here is", "there is"], pos: "adv" },
  { rank: 75, word: "vieux", translations: ["old"], pos: "adj" },
  { rank: 76, word: "monde", translations: ["world", "people"], pos: "n" },
  { rank: 77, word: "non", translations: ["no"], pos: "adv" },
  { rank: 78, word: "jamais", translations: ["never", "ever"], pos: "adv" },
  { rank: 79, word: "main", translations: ["hand"], pos: "n" },
  { rank: 80, word: "œil", translations: ["eye"], pos: "n" },
  { rank: 81, word: "rester", translations: ["to stay", "to remain"], pos: "v" },
  { rank: 82, word: "enfant", translations: ["child"], pos: "n" },
  { rank: 83, word: "alors", translations: ["then", "so"], pos: "adv" },
  { rank: 84, word: "premier", translations: ["first"], pos: "adj" },
  { rank: 85, word: "deux", translations: ["two"], pos: "num" },
  { rank: 86, word: "petit", translations: ["small", "little"], pos: "adj" },
  { rank: 87, word: "comprendre", translations: ["to understand"], pos: "v" },
  { rank: 88, word: "encore", translations: ["still", "yet", "again"], pos: "adv" },
  { rank: 89, word: "vie", translations: ["life"], pos: "n" },
  { rank: 90, word: "fois", translations: ["time", "occasion"], pos: "n" },
  { rank: 91, word: "rien", translations: ["nothing"], pos: "pron" },
  { rank: 92, word: "passer", translations: ["to pass", "to spend"], pos: "v" },
  { rank: 93, word: "regarder", translations: ["to look at", "to watch"], pos: "v" },
  { rank: 94, word: "aimer", translations: ["to love", "to like"], pos: "v" },
  { rank: 95, word: "mère", translations: ["mother"], pos: "n" },
  { rank: 96, word: "mot", translations: ["word"], pos: "n" },
  { rank: 97, word: "lieu", translations: ["place"], pos: "n" },
  { rank: 98, word: "monsieur", translations: ["sir", "Mr."], pos: "n" },
  { rank: 99, word: "vrai", translations: ["true", "real"], pos: "adj" },
  { rank: 100, word: "demander", translations: ["to ask", "to request"], pos: "v" },
  // 101-200
  { rank: 101, word: "trois", translations: ["three"], pos: "num" },
  { rank: 102, word: "année", translations: ["year"], pos: "n" },
  { rank: 103, word: "porter", translations: ["to carry", "to wear"], pos: "v" },
  { rank: 104, word: "parler", translations: ["to speak", "to talk"], pos: "v" },
  { rank: 105, word: "personne", translations: ["person", "nobody"], pos: "n" },
  { rank: 106, word: "tête", translations: ["head"], pos: "n" },
  { rank: 107, word: "moins", translations: ["less", "fewer"], pos: "adv" },
  { rank: 108, word: "depuis", translations: ["since", "for"], pos: "prep" },
  { rank: 109, word: "côté", translations: ["side"], pos: "n" },
  { rank: 110, word: "moment", translations: ["moment"], pos: "n" },
  { rank: 111, word: "moi-même", translations: ["myself"], pos: "pron" },
  { rank: 112, word: "yeux", translations: ["eyes"], pos: "n" },
  { rank: 113, word: "ainsi", translations: ["thus", "in this way"], pos: "adv" },
  { rank: 114, word: "longtemps", translations: ["a long time"], pos: "adv" },
  { rank: 115, word: "déjà", translations: ["already"], pos: "adv" },
  { rank: 116, word: "famille", translations: ["family"], pos: "n" },
  { rank: 117, word: "père", translations: ["father"], pos: "n" },
  { rank: 118, word: "ami", translations: ["friend"], pos: "n" },
  { rank: 119, word: "tenir", translations: ["to hold", "to keep"], pos: "v" },
  { rank: 120, word: "heure", translations: ["hour", "time"], pos: "n" },
  { rank: 121, word: "ville", translations: ["city", "town"], pos: "n" },
  { rank: 122, word: "tellement", translations: ["so much"], pos: "adv" },
  { rank: 123, word: "écouter", translations: ["to listen"], pos: "v" },
  { rank: 124, word: "perdre", translations: ["to lose"], pos: "v" },
  { rank: 125, word: "puis", translations: ["then", "next"], pos: "adv" },
  { rank: 126, word: "appeler", translations: ["to call"], pos: "v" },
  { rank: 127, word: "longueur", translations: ["length"], pos: "n" },
  { rank: 128, word: "loin", translations: ["far"], pos: "adv" },
  { rank: 129, word: "toujours", translations: ["always"], pos: "adv" },
  { rank: 130, word: "haut", translations: ["high", "tall"], pos: "adj" },
  { rank: 131, word: "beau", translations: ["beautiful", "handsome"], pos: "adj" },
  { rank: 132, word: "nouveau", translations: ["new"], pos: "adj" },
  { rank: 133, word: "écrire", translations: ["to write"], pos: "v" },
  { rank: 134, word: "fond", translations: ["bottom", "background"], pos: "n" },
  { rank: 135, word: "tirer", translations: ["to pull", "to shoot"], pos: "v" },
  { rank: 136, word: "soir", translations: ["evening"], pos: "n" },
  { rank: 137, word: "apporter", translations: ["to bring"], pos: "v" },
  { rank: 138, word: "lire", translations: ["to read"], pos: "v" },
  { rank: 139, word: "toi", translations: ["you (informal)"], pos: "pron" },
  { rank: 140, word: "porte", translations: ["door"], pos: "n" },
  { rank: 141, word: "matin", translations: ["morning"], pos: "n" },
  { rank: 142, word: "rendre", translations: ["to return", "to give back"], pos: "v" },
  { rank: 143, word: "place", translations: ["place", "square"], pos: "n" },
  { rank: 144, word: "raison", translations: ["reason"], pos: "n" },
  { rank: 145, word: "manière", translations: ["way", "manner"], pos: "n" },
  { rank: 146, word: "trop", translations: ["too", "too much"], pos: "adv" },
  { rank: 147, word: "fille", translations: ["girl", "daughter"], pos: "n" },
  { rank: 148, word: "noir", translations: ["black"], pos: "adj" },
  { rank: 149, word: "loi", translations: ["law"], pos: "n" },
  { rank: 150, word: "blanc", translations: ["white"], pos: "adj" },
  { rank: 151, word: "présent", translations: ["present"], pos: "adj" },
  { rank: 152, word: "espèce", translations: ["species", "kind"], pos: "n" },
  { rank: 153, word: "souvent", translations: ["often"], pos: "adv" },
  { rank: 154, word: "voir", translations: ["to see"], pos: "v" },
  { rank: 155, word: "fait", translations: ["fact", "done"], pos: "n" },
  { rank: 156, word: "ouvrir", translations: ["to open"], pos: "v" },
  { rank: 157, word: "premier", translations: ["first"], pos: "adj" },
  { rank: 158, word: "mer", translations: ["sea"], pos: "n" },
  { rank: 159, word: "chose", translations: ["thing"], pos: "n" },
  { rank: 160, word: "arriver", translations: ["to arrive", "to happen"], pos: "v" },
  { rank: 161, word: "long", translations: ["long"], pos: "adj" },
  { rank: 162, word: "chez", translations: ["at the home of"], pos: "prep" },
  { rank: 163, word: "fenêtre", translations: ["window"], pos: "n" },
  { rank: 164, word: "pourquoi", translations: ["why"], pos: "adv" },
  { rank: 165, word: "guerre", translations: ["war"], pos: "n" },
  { rank: 166, word: "petit-fils", translations: ["grandson"], pos: "n" },
  { rank: 167, word: "rouge", translations: ["red"], pos: "adj" },
  { rank: 168, word: "cœur", translations: ["heart"], pos: "n" },
  { rank: 169, word: "monter", translations: ["to climb", "to go up"], pos: "v" },
  { rank: 170, word: "compter", translations: ["to count"], pos: "v" },
  { rank: 171, word: "soldat", translations: ["soldier"], pos: "n" },
  { rank: 172, word: "rue", translations: ["street"], pos: "n" },
  { rank: 173, word: "frère", translations: ["brother"], pos: "n" },
  { rank: 174, word: "mauvais", translations: ["bad"], pos: "adj" },
  { rank: 175, word: "loin", translations: ["far"], pos: "adv" },
  { rank: 176, word: "garçon", translations: ["boy"], pos: "n" },
  { rank: 177, word: "voix", translations: ["voice"], pos: "n" },
  { rank: 178, word: "parti", translations: ["party (political)"], pos: "n" },
  { rank: 179, word: "force", translations: ["force", "strength"], pos: "n" },
  { rank: 180, word: "sentir", translations: ["to feel", "to smell"], pos: "v" },
  { rank: 181, word: "moitié", translations: ["half"], pos: "n" },
  { rank: 182, word: "sembler", translations: ["to seem"], pos: "v" },
  { rank: 183, word: "pied", translations: ["foot"], pos: "n" },
  { rank: 184, word: "chercher", translations: ["to look for", "to search"], pos: "v" },
  { rank: 185, word: "hier", translations: ["yesterday"], pos: "adv" },
  { rank: 186, word: "court", translations: ["short"], pos: "adj" },
  { rank: 187, word: "vite", translations: ["fast", "quickly"], pos: "adv" },
  { rank: 188, word: "demain", translations: ["tomorrow"], pos: "adv" },
  { rank: 189, word: "moindre", translations: ["least", "smallest"], pos: "adj" },
  { rank: 190, word: "doute", translations: ["doubt"], pos: "n" },
  { rank: 191, word: "ouvrage", translations: ["work", "book"], pos: "n" },
  { rank: 192, word: "mort", translations: ["death", "dead"], pos: "n" },
  { rank: 193, word: "perdu", translations: ["lost"], pos: "adj" },
  { rank: 194, word: "pendant", translations: ["during", "while"], pos: "prep" },
  { rank: 195, word: "fort", translations: ["strong"], pos: "adj" },
  { rank: 196, word: "histoire", translations: ["history", "story"], pos: "n" },
  { rank: 197, word: "tomber", translations: ["to fall"], pos: "v" },
  { rank: 198, word: "raison", translations: ["reason"], pos: "n" },
  { rank: 199, word: "important", translations: ["important"], pos: "adj" },
  { rank: 200, word: "esprit", translations: ["spirit", "mind"], pos: "n" },
  // 201-300
  { rank: 201, word: "marcher", translations: ["to walk"], pos: "v" },
  { rank: 202, word: "souvenir", translations: ["memory", "souvenir"], pos: "n" },
  { rank: 203, word: "chambre", translations: ["room", "bedroom"], pos: "n" },
  { rank: 204, word: "jeune", translations: ["young"], pos: "adj" },
  { rank: 205, word: "français", translations: ["French"], pos: "adj" },
  { rank: 206, word: "entrer", translations: ["to enter"], pos: "v" },
  { rank: 207, word: "silence", translations: ["silence"], pos: "n" },
  { rank: 208, word: "côté", translations: ["side"], pos: "n" },
  { rank: 209, word: "froid", translations: ["cold"], pos: "adj" },
  { rank: 210, word: "feu", translations: ["fire"], pos: "n" },
  { rank: 211, word: "argent", translations: ["money", "silver"], pos: "n" },
  { rank: 212, word: "sortir", translations: ["to go out"], pos: "v" },
  { rank: 213, word: "pays", translations: ["country"], pos: "n" },
  { rank: 214, word: "chemin", translations: ["path", "way"], pos: "n" },
  { rank: 215, word: "paraître", translations: ["to appear"], pos: "v" },
  { rank: 216, word: "asseoir", translations: ["to sit"], pos: "v" },
  { rank: 217, word: "haute", translations: ["high (fem.)"], pos: "adj" },
  { rank: 218, word: "lever", translations: ["to raise", "to get up"], pos: "v" },
  { rank: 219, word: "âge", translations: ["age"], pos: "n" },
  { rank: 220, word: "mois", translations: ["month"], pos: "n" },
  { rank: 221, word: "battre", translations: ["to beat", "to hit"], pos: "v" },
  { rank: 222, word: "sœur", translations: ["sister"], pos: "n" },
  { rank: 223, word: "verre", translations: ["glass"], pos: "n" },
  { rank: 224, word: "matin", translations: ["morning"], pos: "n" },
  { rank: 225, word: "pierre", translations: ["stone"], pos: "n" },
  { rank: 226, word: "jeter", translations: ["to throw"], pos: "v" },
  { rank: 227, word: "presque", translations: ["almost"], pos: "adv" },
  { rank: 228, word: "boire", translations: ["to drink"], pos: "v" },
  { rank: 229, word: "manger", translations: ["to eat"], pos: "v" },
  { rank: 230, word: "couleur", translations: ["color"], pos: "n" },
  { rank: 231, word: "espérer", translations: ["to hope"], pos: "v" },
  { rank: 232, word: "lumière", translations: ["light"], pos: "n" },
  { rank: 233, word: "milieu", translations: ["middle"], pos: "n" },
  { rank: 234, word: "armée", translations: ["army"], pos: "n" },
  { rank: 235, word: "bord", translations: ["edge", "side"], pos: "n" },
  { rank: 236, word: "voiture", translations: ["car"], pos: "n" },
  { rank: 237, word: "plein", translations: ["full"], pos: "adj" },
  { rank: 238, word: "maître", translations: ["master", "teacher"], pos: "n" },
  { rank: 239, word: "courir", translations: ["to run"], pos: "v" },
  { rank: 240, word: "vivre", translations: ["to live"], pos: "v" },
  { rank: 241, word: "table", translations: ["table"], pos: "n" },
  { rank: 242, word: "lit", translations: ["bed"], pos: "n" },
  { rank: 243, word: "rappeler", translations: ["to remind", "to call back"], pos: "v" },
  { rank: 244, word: "bras", translations: ["arm"], pos: "n" },
  { rank: 245, word: "envoyer", translations: ["to send"], pos: "v" },
  { rank: 246, word: "respect", translations: ["respect"], pos: "n" },
  { rank: 247, word: "ineffable", translations: ["ineffable", "unutterable"], pos: "adj" },
  { rank: 248, word: "neige", translations: ["snow"], pos: "n" },
  { rank: 249, word: "soleil", translations: ["sun"], pos: "n" },
  { rank: 250, word: "ciel", translations: ["sky", "heaven"], pos: "n" },
  { rank: 251, word: "voler", translations: ["to fly", "to steal"], pos: "v" },
  { rank: 252, word: "nuit", translations: ["night"], pos: "n" },
  { rank: 253, word: "lune", translations: ["moon"], pos: "n" },
  { rank: 254, word: "étoile", translations: ["star"], pos: "n" },
  { rank: 255, word: "rêve", translations: ["dream"], pos: "n" },
  { rank: 256, word: "oublier", translations: ["to forget"], pos: "v" },
  { rank: 257, word: "pleurer", translations: ["to cry"], pos: "v" },
  { rank: 258, word: "rire", translations: ["to laugh"], pos: "v" },
  { rank: 259, word: "chanter", translations: ["to sing"], pos: "v" },
  { rank: 260, word: "danser", translations: ["to dance"], pos: "v" },
  { rank: 261, word: "musique", translations: ["music"], pos: "n" },
  { rank: 262, word: "livre", translations: ["book", "pound"], pos: "n" },
  { rank: 263, word: "papier", translations: ["paper"], pos: "n" },
  { rank: 264, word: "peindre", translations: ["to paint"], pos: "v" },
  { rank: 265, word: "image", translations: ["image", "picture"], pos: "n" },
  { rank: 266, word: "regard", translations: ["look", "gaze"], pos: "n" },
  { rank: 267, word: "visage", translations: ["face"], pos: "n" },
  { rank: 268, word: "bouche", translations: ["mouth"], pos: "n" },
  { rank: 269, word: "sourire", translations: ["to smile", "smile"], pos: "v" },
  { rank: 270, word: "embrasser", translations: ["to kiss", "to embrace"], pos: "v" },
  { rank: 271, word: "amour", translations: ["love"], pos: "n" },
  { rank: 272, word: "haine", translations: ["hate"], pos: "n" },
  { rank: 273, word: "peur", translations: ["fear"], pos: "n" },
  { rank: 274, word: "joie", translations: ["joy"], pos: "n" },
  { rank: 275, word: "tristesse", translations: ["sadness"], pos: "n" },
  { rank: 276, word: "colère", translations: ["anger"], pos: "n" },
  { rank: 277, word: "espoir", translations: ["hope"], pos: "n" },
  { rank: 278, word: "doux", translations: ["sweet", "soft"], pos: "adj" },
  { rank: 279, word: "amer", translations: ["bitter"], pos: "adj" },
  { rank: 280, word: "fort", translations: ["strong"], pos: "adj" },
  { rank: 281, word: "faible", translations: ["weak"], pos: "adj" },
  { rank: 282, word: "lourd", translations: ["heavy"], pos: "adj" },
  { rank: 283, word: "léger", translations: ["light (weight)"], pos: "adj" },
  { rank: 284, word: "rapide", translations: ["fast", "quick"], pos: "adj" },
  { rank: 285, word: "lent", translations: ["slow"], pos: "adj" },
  { rank: 286, word: "facile", translations: ["easy"], pos: "adj" },
  { rank: 287, word: "difficile", translations: ["difficult"], pos: "adj" },
  { rank: 288, word: "possible", translations: ["possible"], pos: "adj" },
  { rank: 289, word: "impossible", translations: ["impossible"], pos: "adj" },
  { rank: 290, word: "vrai", translations: ["true"], pos: "adj" },
  { rank: 291, word: "faux", translations: ["false"], pos: "adj" },
  { rank: 292, word: "ouvert", translations: ["open"], pos: "adj" },
  { rank: 293, word: "fermé", translations: ["closed"], pos: "adj" },
  { rank: 294, word: "plein", translations: ["full"], pos: "adj" },
  { rank: 295, word: "vide", translations: ["empty"], pos: "adj" },
  { rank: 296, word: "propre", translations: ["clean", "own"], pos: "adj" },
  { rank: 297, word: "sale", translations: ["dirty"], pos: "adj" },
  { rank: 298, word: "neuf", translations: ["new", "nine"], pos: "adj" },
  { rank: 299, word: "vieux", translations: ["old"], pos: "adj" },
  { rank: 300, word: "même", translations: ["same"], pos: "adj" },
];

window.SEED_VOCAB.forEach((v, i) => {
  v.id = `card_seed_${String(v.rank).padStart(5, '0')}`;
  v.miniDeck = Math.floor(i / 100) + 1; // 1, 2, 3...
  v.encounters = 0;
  v.bookSentences = []; // [{book, sentence, hidden_word_index}]
});

// 頻出構文50文（標準装備）
window.SEED_PHRASES = [
  { fr: "Comment ça va ?", en: ["How are you?"] },
  { fr: "Qu'est-ce que c'est ?", en: ["What is it?", "What is this?"] },
  { fr: "Je ne sais pas.", en: ["I don't know."] },
  { fr: "Je voudrais un café, s'il vous plaît.", en: ["I would like a coffee, please."] },
  { fr: "Combien ça coûte ?", en: ["How much does it cost?"] },
  { fr: "Où sont les toilettes ?", en: ["Where is the bathroom?"] },
  { fr: "Je suis désolé.", en: ["I'm sorry."] },
  { fr: "Pouvez-vous m'aider ?", en: ["Can you help me?"] },
  { fr: "Je ne comprends pas.", en: ["I don't understand."] },
  { fr: "Parlez-vous anglais ?", en: ["Do you speak English?"] },
  { fr: "Qu'est-ce que tu fais ?", en: ["What are you doing?"] },
  { fr: "Il fait beau aujourd'hui.", en: ["The weather is nice today."] },
  { fr: "J'ai faim.", en: ["I'm hungry."] },
  { fr: "J'ai soif.", en: ["I'm thirsty."] },
  { fr: "C'est combien ?", en: ["How much is it?"] },
  { fr: "Je m'appelle...", en: ["My name is..."] },
  { fr: "Enchanté de faire votre connaissance.", en: ["Pleased to meet you."] },
  { fr: "À bientôt.", en: ["See you soon."] },
  { fr: "Bonne journée.", en: ["Have a good day."] },
  { fr: "Bonne nuit.", en: ["Good night."] },
  { fr: "Il faut que je parte.", en: ["I have to leave.", "I need to go."] },
  { fr: "Ça m'est égal.", en: ["I don't care.", "It's all the same to me."] },
  { fr: "Ça vaut la peine.", en: ["It's worth it."] },
  { fr: "Je suis en train de travailler.", en: ["I'm in the process of working.", "I'm working right now."] },
  { fr: "Ça fait longtemps.", en: ["It's been a long time."] },
  { fr: "Tu me manques.", en: ["I miss you."] },
  { fr: "Ça dépend.", en: ["It depends."] },
  { fr: "Je suis d'accord.", en: ["I agree."] },
  { fr: "Pas du tout.", en: ["Not at all."] },
  { fr: "Au contraire.", en: ["On the contrary."] },
  { fr: "À vrai dire...", en: ["To tell the truth...", "Honestly..."] },
  { fr: "En fait...", en: ["Actually...", "In fact..."] },
  { fr: "Tout à fait.", en: ["Absolutely.", "Exactly."] },
  { fr: "Bien sûr.", en: ["Of course."] },
  { fr: "Pourquoi pas ?", en: ["Why not?"] },
  { fr: "Ça ne fait rien.", en: ["It doesn't matter.", "Never mind."] },
  { fr: "C'est dommage.", en: ["That's a shame."] },
  { fr: "Tant pis.", en: ["Too bad.", "Oh well."] },
  { fr: "Tant mieux.", en: ["So much the better."] },
  { fr: "Il y a longtemps que...", en: ["It's been a long time since..."] },
  { fr: "Je n'en peux plus.", en: ["I can't take it anymore."] },
  { fr: "Ne t'inquiète pas.", en: ["Don't worry."] },
  { fr: "Fais attention.", en: ["Be careful."] },
  { fr: "C'est ma faute.", en: ["It's my fault."] },
  { fr: "Tu as raison.", en: ["You're right."] },
  { fr: "Je n'y arrive pas.", en: ["I can't manage it."] },
  { fr: "Ça vient.", en: ["It's coming.", "It's almost there."] },
  { fr: "On y va.", en: ["Let's go."] },
  { fr: "À tout à l'heure.", en: ["See you later."] },
  { fr: "Je te tiens au courant.", en: ["I'll keep you posted."] },
];

window.SEED_PHRASES.forEach((p, i) => {
  p.id = `phrase_seed_${String(i + 1).padStart(4, '0')}`;
  p.type = 'sentence';
  p.source = 'standard';
});
